name: Markdown link check

on:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: umbrelladocs/action-linkspector@v1
      with:
        fail_on_error: true
